### ISSUE TITLE
Can't compile chakracore-sys

### ISSUE THREAD

**Issue by rosshadden** [darfink/jsrt-rs#3]
When trying to build, I get the following errors:

![2017-02-08-16 33 47](https://cloud.githubusercontent.com/assets/669012/22758367/6ba5216c-ee1c-11e6-89d3-bdca8e80ad25.png)

![2017-02-08-16 34 22](https://cloud.githubusercontent.com/assets/669012/22758374/77e6cd9a-ee1c-11e6-910c-4c0d20417656.png)

**Comment by darfink** [comment]
These were because of incompatibilities with the latest `bindgen`.
Fixed and published with version `0.2.0`.
