### ISSUE TITLE
Runtime is not Send

### ISSUE THREAD

**Issue by srijs** [darfink/jsrt-rs#4]
Hi!

According to the Chakracore JSRT [docs](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview), runtimes "[...] are rental threaded, so a runtime that is not currently active on a thread (i.e. isn’t running any JavaScript code or responding to any calls from the host) can be used on any thread that doesn’t already have an active runtime on it.".

The way I understand it is that Runtime should implement `Send`, so it can be sent between threads. However, trying to send a runtime between threads results in the following errors:

```
error[E0277]: the trait bound `*mut libc::c_void: std::marker::Send` is not satisfied in `js::Runtime`
   = help: within `js::Runtime`, the trait `std::marker::Send` is not implemented for `*mut libc::c_void`
   = note: required because it appears within the type `chakracore_sys::JsRuntimeHandle`
   = note: required because it appears within the type `js::Runtime`
```

```
error[E0277]: the trait bound `std::ops::Fn() + 'static: std::marker::Send` is not satisfied
   = help: the trait `std::marker::Send` is not implemented for `std::ops::Fn() + 'static`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<std::ops::Fn() + 'static>`
   = note: required because it appears within the type `std::boxed::Box<std::ops::Fn() + 'static>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<std::boxed::Box<std::ops::Fn() + 'static>>`
   = note: required because it appears within the type `std::boxed::Box<std::boxed::Box<std::ops::Fn() + 'static>>`
   = note: required because it appears within the type `std::option::Option<std::boxed::Box<std::boxed::Box<std::ops::Fn() + 'static>>>`
   = note: required because it appears within the type `js::Runtime`
```

**Comment by darfink** [comment]
You are correct.

I've marked the underlying `JsRuntimeHandle` as `Send` — 3da23fd3a7dce0d455f80ea2c0611d305856e8dc.
I've also made the necessary changes in `Runtime` — 6079e22c6a2f3275051c87736b3c26cad8fd9414.

I will publish all the latest changes on *Crates.io* as soon as I've tested the new build changes on Windows, and fully implemented `Promise` as a value type.
