### ISSUE TITLE
Expose JsGetAndClearException API

### ISSUE THREAD

**Issue by srijs** [darfink/jsrt-rs#5]
Quoting the [JSRT docs](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview):

> When a JavaScript exception occurs during script execution, the containing runtime is put into an exception state. While in an exception state, no code can run and all API calls will fail with the error code JsErrorInExceptionState until the host retrieves and clears the exception using the JsGetAndClearException API.

It would be useful to expose the `JsGetAndClearException` API on the context so the runtime can continue to be used after an exception occurred.

EDIT: Reading through the source code I noticed that most places use `util::handle_exception` to do just that. I might've run into an edge-case where it doesn't do that. Let me try to narrow down the problem.

**Comment by srijs** [comment]
It appears the core of the problem is that when a parse error occurs during loading a script, the JSRT fails with `JsErrorCode::ScriptCompile`, but `util::handle_exception` only picks up on `JsErrorCode::ScriptException`.

**Comment by darfink** [comment]
Yes, as you've noticed, the runtime exception state is intended to be opaque to the user.
Thanks a ton for the PR! I'll most likely merge it tomorrow, with accompanying unit tests.
